spring:
  application:
    name: Employee_Management_System
  datasource:
    url: jdbc:h2:emp:employee
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
